name: icon_background_issue
description:
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.14.4 <3.0.0'
  flutter: ^2.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: true
  image_path: images/dash.png
  adaptive_icon_background: '#000000'